### ISSUE TITLE
cannot login after install

### ISSUE THREAD

**Issue by f2h2h1** [dotproject/dotProject#219]
i use docker-compose for install,
but after install i cannot login,
always redirect to index.php

environment
- branch: devel
- commit id: aca232be48501c59ecb48d289ea5896c8d079a9b
- login account: admin/passwd

**Comment by f2h2h1** [comment]
Although I couldn't find the root cause, I modified the file `docker-compose.yml` and the installation was successful

For reference only

environment
- branch: devel
- commit id: https://github.com/dotproject/dotProject/commit/aca232be48501c59ecb48d289ea5896c8d079a9b

./docker-compose/Dockerfile
```
FROM php:7.4-apache

RUN docker-php-ext-install pdo pdo_mysql mysqli
RUN cp /usr/local/etc/php/php.ini-development /usr/local/etc/php/php.ini
RUN sed -i 's/;session.save_path = "\/tmp"/session.save_path = "\/tmp"/' /usr/local/etc/php/php.ini

CMD ["apache2-foreground"]
```

./docker-compose.yml
```
version: '3.7'
services:
  mariadb:
    image: mariadb:10.4
    restart: always
    volumes:
      - ./dpdb:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: secretpw
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}

  phpapache:
    build: ./.docker-compose
    image: php:7.4-apache
    restart: always
    depends_on:
      - "mariadb"
    volumes:
      - ./:/var/www/html
    ports:
      - "8080:80"

  phpmyadmin:
    image: phpmyadmin:5.2-apache
    restart: always
    depends_on:
      - "mariadb"
    ports:
      - "8081:80"
    environment:
      PMA_HOST: mariadb

```

Finally, the file `session.save_path` should be writable
